### ISSUE TITLE
Using with wine

### ISSUE THREAD

**Issue by mobedoor** [0xDC00/agent#10]
Is this usable with wine? Any steps, if documented? 
Thanks

**Comment by 0xDC00** [comment]
Agent is an electron app,

try: `wine agent.exe` or `wine agent.exe --disable-gpu --no-sandbox`.

**Comment by mobedoor** [comment]
Sorry for not being clearer. I meant does this work with wine games if you're using the linux build?

**Comment by 0xDC00** [comment]
Depends on the script, just try...

Agent (linux) => wine (target win32);

Another solution (frida-server running inside wine):
Agent (linux) => frida-server => target
then input Target: `127.0.0.1:27042` (frida-server ip:port)
But only support mobile for now (frontmost target).
For PC, need implement process picker.

**Comment by mobedoor** [comment]
Thanks for the info. I was asking for desktop so will have to wait.

**Comment by 0xDC00** [comment]
Latest release added remote frida-server support.
