### ISSUE TITLE
registerblock not found

### ISSUE THREAD

**Issue by Donteatorbefat** [0xDC00/agent#13]
sorry, im trying to use the scripts in agent (i tried with the older versions and this new one) but when i put them so i can translate the games it appears an error that says registerblock not found and idk what to do, i hope there is a solution...

**Comment by 0xDC00** [comment]
@Donteatorbefat Update scripts
[https://www.youtube.com/watch?v=c0aVSr_nYJ0&list=PLTZXVVG9AT6Sbl1Yg42sxzVAS6IMfnaNH](https://www.youtube.com/watch?v=c0aVSr_nYJ0&list=PLTZXVVG9AT6Sbl1Yg42sxzVAS6IMfnaNH)
