### ISSUE TITLE
Running on linux

### ISSUE THREAD

**Issue by WilsonNet** [0xDC00/agent#17]
I can't run on Linux, it seems to me the Linux version is a pre-compiled binary. I imagine that is an Ubuntu binary and I'm on Manjaro.
It would be nice if it was packed in a distro-agnostic format like [Flatpack](https://docs.flatpak.org/en/latest/first-build.html), since I don't have the source code to compile myself.

**Comment by mobedoor** [comment]
Works fine over here. I'm on EndeavousOS which is also Arch based.

**Comment by 0xDC00** [comment]
Port Agent to Linux or macOS (outdated but works):
<https://docs.google.com/document/d/1AaNWX_oEWdcRRBascMcC8_hluCDoDkt2rjOG-ChqZ0M/edit>

Agent 0.1.3
Frida: 16.x
Electron: 21.x

**Comment by WilsonNet** [comment]
Thanks, turns out I just had to change the permissions with `chmod +x`
