### ISSUE TITLE
Query regarding ExecutionWatch

### ISSUE THREAD

**Issue by ZDTL** [0xDC00/agent#2]
So, I tried to find the D-Code of Tantei Bokumetsu 1.0.2 and was successful. I also had a pattern from before so it was easy to judge.

Now I am trying to find out the D-Code for Buddy Mission Bond (https://vndb.org/v30145) 1.0.1

It has shift_jis encoding. 

I tried to follow your steps and found out 4 addresses
![G307P8N2at](https://user-images.githubusercontent.com/33268074/125739374-b7ce2a71-1a15-4ba0-87e6-3b247c883341.png)
The third address showed instructions when I moved to the dialog B from A.

It had these many instructions with low count (address is different because CE crashed but I followed the same steps from before)
![cheatengine-x86_64-SSE4-AVX2_kBotcMLuPY](https://user-images.githubusercontent.com/33268074/125739529-daa77400-2ea3-4b1e-88ac-dc5c26462fb3.png)

For the time being, I selected the 4th one because it had similar pattern from your tutorial (movzx, byte ptr).

But I don't know where to stop. Is it [eax, address] ?
![cheatengine-x86_64-SSE4-AVX2_Hrl8sn40js](https://user-images.githubusercontent.com/33268074/125739776-73fe554a-6394-4f46-a2fe-8b4bee0c11e8.png)

So I have two questions regarding your explanation in wiki:

**1. How do I find out the TerminatedPattern for a particular game? 
2. In Step 3 from your tutorial where I am checking instructions, how do I decide the range of addresses to copy from memory viewer?**

**Comment by 0xDC00** [comment]
1. Terminated
Normal case <https://en.wikipedia.org/wiki/Null-terminated_string>:
- utf-8, shift_jis: 00
- utf-16: 0000
- utf-32: 00000000

Ex:
```
line1
line2
```
=>
`00000000  6C696E65 310A6C69 6E653200 00000000  line1.line2.....`
But some games use '00' for line break (instead 0A), the sequence will become:
`00000000  6C696E65 31006C69 6E653200 00000000  line1.line2.....`

If we use `00` for terminated (instead 0000),
we only get `6C696E653100` <=> line1.

#3 the game use custom-terminated.

2. The length can be any, just make sure your pattern matches only one result.
Looks like this game needs manual debugging to find a good hook.
