### ISSUE TITLE
Error: RegisterBlock not found! 

### ISSUE THREAD

**Issue by J6359** [0xDC00/agent#23]
Error: RegisterBlock not found!
' at getDoJitAddress (<input>:80)
at <anonymous> (<input>:10)
at call (native)
at <eval> (<input>:213)
at load (/agent.js:1)
at _loadModule (/agent.js:l)
_ at <anonymous> (/agent.js:l)
‘ at require (/agent.js:l)
} at <anonymous> (<input>: 9)
at call (native)
J at <eval> (<input>:116)
[ at load (/agent.js:1)
at _loadMod111e (/agent.js:1)
‘ at <anonymous> (/agent.js:1)
L at main (/agent.js:l)
2 at <anonymous> (/agent.js:1)
) at <eval> (/agent.js:1)

**Comment by J6359** [comment]
what i have to do for resolve that

**Comment by 0xDC00** [comment]
Quickstart: https://youtu.be/dFfuq2UnKjU
