### ISSUE TITLE
Error: Emulated realm is not supported on this OS

### ISSUE THREAD

**Issue by Potatoesgod** [0xDC00/agent#24]
So i was trying to play Kamigami no asobi Infinite on an emulator of psp , but when i tried to attach it gives me this error "Error: Emulated realm is not supported on this OS". The version of the psp emulator is 1.15.4 and agent is in v0.1.3 . So any solution to this?

**Comment by kdw-code** [comment]
Disable realms option in the translate tab. It's supposed to be turned off by default.
You only need to turn that on when you play android games

**Comment by Potatoesgod** [comment]
Thanks now it works ^^
