### ISSUE TITLE
P5R Steam Detach process

### ISSUE THREAD

**Issue by noxxid3** [0xDC00/agent#26]
I get agent working on any other game but there is a issue with the steam version where it automatically detaches itself from the game after a successful launch and loading script.
![image](https://github.com/0xDC00/agent/assets/19700465/0034cca1-5b51-4e3e-a31a-10a2e0829009)

NOTE: There is no downgrade for this game, only different languages in the manifests. 

// ==UserScript==
// @name         Persona 5 Royal
// @version      0.1
// @author       Koukdw & [DC]
// @description  Windows
// * Atlus
// * 

Run:
- D:\Steam\steamapps\common\P5R\P5R.exe
- D:\Documents\Japanese\Agent\data\scripts\PC_Steam_Persona_5_Royal.js
Device:     [local] Local System
TargetPID:  12768
[+] Script Init
[+] Agent loaded:  D:\Documents\Japanese\Agent\data\scripts\PC_Steam_Persona_5_Royal.js
[*] Detached from process (reason=process-terminated)

No idea why it is doing this. I tried drag and drop but continues to detach from process with zero indication as to why.

**Comment by 0xDC00** [comment]
Quickstart: https://youtu.be/dFfuq2UnKjU
