### ISSUE TITLE
The new Yuzu (12??+) broke some scripts.   

### ISSUE THREAD

**Issue by Lexaed** [0xDC00/agent#28]
The new Yuzu (12??+) broke some scripts.
  FIX: Yuzu -> Configuration -> General -> Debug:
    Tab Debug => check 'Enable CPU Debugging' (Advanced section)
    Tab CPU   => uncheck 'Enable block linking'
   -> OK (apply changes -> restart game)
I am trying to hook tsukihime text from the game, yet when I try to attach the game to the agent, it just says the thing about broken scrpits and fix. I did the fix, but nothing has changed, I can't extract the text, what can I do?

(Updated scripts are checked)

**Comment by kdw-code** [comment]
Most likely you didn't install any update. 
At the top of the script it's written which patch the script is for.
For tsukihime it's 1.0.1 and 1.0.2 (both are supported)

**Comment by Lexaed** [comment]
> Most likely you didn't install any update. At the top of the script it's written which patch the script is for. For tsukihime it's 1.0.1 and 1.0.2 (both are supported)

I had 1.02 patch installed

**Comment by kdw-code** [comment]
Try an older version of yuzu

**Comment by jenyjj** [comment]
The same thing happens to me, and it is not an option to have the yuzu of the previous version because it does not read the XCI or eSHOP games
another solution please

**Comment by kdw-code** [comment]
Update your scripts
