### ISSUE TITLE
Script not showing up using Yuzu

### ISSUE THREAD

**Issue by Sunnelia** [0xDC00/agent#31]
So when the agent is attached and I click to proceed with text it (idk how to word it) the script does not show up on agent. I tried redownloading/updating Yuzu also tried redownloading agent. 
I do everything according to the guide and also used agent a few times back in June and didn't have this problem

**Comment by 0xDC00** [comment]
Title ID, version?
Btw, please check new quickstart: https://youtu.be/dFfuq2UnKjU

**Comment by Sunnelia** [comment]
> Title ID, version? Btw, please check new quickstart: https://youtu.be/dFfuq2UnKjU

Okay so I did fix it, the problem was that I had single window mode turned off. Although other two games work one still doesn't I only get this message (also if Yuzu's version you were asking for it's 1656)
![image_2023-12-23_225724962](https://github.com/0xDC00/agent/assets/135891302/50f3e1db-4194-41c7-995e-151500f82c09)

**Comment by kdw-code** [comment]
That game script have problem. It need to be fixed but i'll do that when i have time.
