### ISSUE TITLE
13 sentinels script (yuzu) doesn't retrieve text in some cases

### ISSUE THREAD

**Issue by ganqqwerty** [0xDC00/agent#34]
For the 比治山隆俊 character, his second scene with delinquents (1985年廃工場裏/0%). The protagonist's phrases are captured by the Agent, but the text that other characters produce is not captured. Agent produces the error message for them: 

```
onEnter name 2 (speech bubble)
onEnter dialogue 2 (speech bubble)
Error: access violation accessing 0x25c66800000
緒方稔二
```

System: Windows 11,
script 1388|yuzu 1675 | 十三機兵防衛圏 (64-bit) | 1.00 | AMD
Agent Version: 0.1.3
Yuzu version 1675 (2024-01-07)

**Comment by SaberActive** [comment]
I encountered this too. In scenes like where BJ is displaying the news castor talking about the current year.

**Comment by ganqqwerty** [comment]
yes, this one
![image](https://github.com/0xDC00/agent/assets/697308/4e726ebd-469f-4256-8c38-74309cd411fd)

**Comment by ganqqwerty** [comment]
another scene where the girl's text is not captured 
![image](https://github.com/0xDC00/agent/assets/697308/31102207-0bad-40c7-9b06-66b105d6ab06)

**Comment by kdw-code** [comment]
That's great but if you ever want me to fix this, you will need to give me a save file with saves just before the problems or fix it yourself. I can't fix this without it, the game is very long i can't spend 5-10 hours playing it just to fix one game.

**Comment by ganqqwerty** [comment]
@koukdw 

Indeed! Here is a save file: 
https://drive.google.com/file/d/1BGDPJ_CQtfGPNrlQ8fFDNT4XxOHtaZyt/view?usp=sharing

Now, here's how to get to problematic episodes.

### Motorcycle episode

Run the game, click Load game and pick the motorcycle episode

### News narrator episode
1. Load the motorcycle episode
2. Play + to load the game menu
3. In the game menu Go to Event Archive (イベントアーカイブ) and pick the events related to the character 南奈津乃 using left and right buttons. The characters are picked in tabs on the top-right part of the screen

The problematic event is 2065 year as shown on screenshot:
![image](https://github.com/0xDC00/agent/assets/697308/59ea90ca-52d4-4433-b7ff-98e34922e3d1)

The problem will start when the cute-robot starts broad casting the hologram with the news.

### Delinquents episode
1. Load the motorcycle episode 
2. Go to the event archive
3. pick the character 比治山隆俊 in the tabs on the tip right of the screen
4. pick the event No 156, that is happening in 1985 as shown on the screen
![image](https://github.com/0xDC00/agent/assets/697308/6a376ab8-6e0d-491e-bc27-64c1eb67432a)

**Comment by ganqqwerty** [comment]
if there's any problem with the Events archive, I can record a video to show what to do. I can also help online on discord or zoom or whatever. Unfortunately it's not possible to save a game when you view the Event archives.

**Comment by kdw-code** [comment]
Thanks that will do. I'll look at it tomorrow

**Comment by kdw-code** [comment]
I can find a better hook for dialogue text, but there's no good hook for the name of the current character

**Comment by kdw-code** [comment]
[NS_010045C014650000_13_Sentinels_Aegis_Rim.zip](https://github.com/0xDC00/agent/files/13953897/NS_010045C014650000_13_Sentinels_Aegis_Rim.zip)

I think i fixed it but test it too

**Comment by ganqqwerty** [comment]
Oh wooow, so quick! Thanks, will test it today!

**Comment by ganqqwerty** [comment]
All scenes that I mentioned work really well now. Now there's no characters' names but IMO it's much more practical like that. I did some regression testing for 10-15 other episodes and everything seems to work perfectly. Thank you so much for your time!!!

Now, I tried to search for good addresses myself using CheatEngine but failed to see the content. Like the text is searchable but I can't view it using any of encodings. Did you use other tool to discover the addresses? I'd love to add descriptions of the battle menus, because they're written in pretty weird font and use complex terminology.

**Comment by kdw-code** [comment]
I used dynarmic tracer script it's on the agent discord. We may publish tools like this in the future when they are more easy to use.
https://discord.com/channels/867944111557201980/888396325345964092/1167233041719103508
I also posted a video of me using it, it's stickied in the same channel
