### ISSUE TITLE
Question regarding finding the D-Code

### ISSUE THREAD

**Issue by disclaudia** [0xDC00/agent#4]
Hi, I am very new to Cheat Engine and Agent in general, and I would like to learn more.

In the first step of finding D-Code, it says to `Save State` at any dialogue (A).
And later on it says to `Load State`

The problem is: I haven't the slightest clue how to, and google hasn't been of much help.
I would really appreciate any assistance.

**Comment by 0xDC00** [comment]
Load State <=> back to previous dialogue <=> restart game.
First, we need to known the next dialogue. (for set breakpoint <=> find out... => then analyze the related functions)
<https://www.youtube.com/watch?v=KlgpU8CnHZc>

This trick can work for many targets PC and Emulators (yuzu, ppsspp,...).
Some targets require more debugging skills.
More: <https://wiki.anime-sharing.com/hgames/index.php?title=AGTH/Tutorial>
It may not easy for newbies...

Good luck.
