### ISSUE TITLE
32-bit processes error on SteamOS

### ISSUE THREAD

**Issue by mathewthe2** [0xDC00/agent#40]
Can there be a 32-bit Frida build for the Linux release for SteamOS?

> Error: Unable to handle 32-bit processes due to build configuration

![image](https://github.com/0xDC00/agent/assets/13146030/15bb5db7-5033-456d-872e-b29b49ba00d7)

**Comment by kdw-code** [comment]
You can't use linux agent for wine/proton games, it's only for native linux games. You need to use windows agent in wine. 
Or you need to use frida server and inside wine and connect to it with linux agent.

**Comment by mathewthe2** [comment]
Thanks, I tried launching the windows agent through proton by adding it as a non-Steam game, but I can't seem to be able to select the game window with that agent.

**Comment by kdw-code** [comment]
in the target box `|<name of the executable>`

**Comment by mathewthe2** [comment]
> Error: Unable to find executable at 'PWAAT.exe'

I read from this [Reddit post ](https://www.reddit.com/r/visualnovels/comments/12ma1t4/comment/jjak5ew/)that on Steam they are ran on separate prefixes.

I tried adding some commands following that post, but to no avail.

**Comment by kdw-code** [comment]
https://youtu.be/ihIT5V8Eexw try this

**Comment by mathewthe2** [comment]
Thanks, I've seen this video once but I thought it wouldn't work since Steam is not installed as flatpak on SteamOS.

I ignored the first 2 steps and followed the installation instructions of [STL](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#install) and got it working.

In misc settings of STL:
- (checked) fork custom command
- (unchecked) only custom command
- (checked) force proton

Clipboard works fine and I'm seeing text pasted on Chrome as well. I'll close this issue.
