### ISSUE TITLE
Replace raw text with translated text

### ISSUE THREAD

**Issue by mspykerez** [0xDC00/agent#6]
Is it possible for the hooked text to be resend back into the game in its translated form like some other tools (VNR) do?

**Comment by 0xDC00** [comment]
It is doable, but unstable.
Each game/engine use it own format (plain text, binary).
Invalid changes (wrong format) may crash the game.

Instead... We can inject another dialogue into the game with ImGUI (ImGUI & Overlay).
![image](https://user-images.githubusercontent.com/29352751/145062266-23d178b1-f0a8-4181-a4bb-7711550ced2b.png)

**Comment by 0xDC00** [comment]
Not related to agent, each game need specific scripts.

Latest Agent has overlay support (ingame):
![image](https://user-images.githubusercontent.com/29352751/205728147-3f2c22aa-9f4d-41d2-9a58-c6d62e781350.png)
