### ISSUE TITLE
[Feature Request] Remember last configuration

### ISSUE THREAD

**Issue by kanjieater** [0xDC00/agent#7]
Love the work on this. I'm trying to get these two boxes to remember what they were last set to, as it's kind of tedious to have to set them both every time you want to play a game.

![image](https://user-images.githubusercontent.com/32607317/144775053-dcbb739d-4d33-4bae-bbc2-b123ec897d5e.png)

**Comment by 0xDC00** [comment]
@kanjieater Please use command line instead.
v0.1.2: [https://github.com/0xDC00/agent/releases/](https://github.com/0xDC00/agent/releases/)
