### ISSUE TITLE
How do I fix "DoJit not found!"

### ISSUE THREAD

**Issue by Einzz148** [0xDC00/agent#8]
I haven't faced this issue before and I'm afraid it's causing the program to not work since no text is being copied to my clipboard :(.

**Comment by zaiman12345** [comment]
I've had the same issue, I think it's probably caused by a recent yuzu update of some kind

**Comment by bluesquares01** [comment]
same issue here :(

**Comment by easonma97** [comment]
same issue

**Comment by Beniamin-Dolega** [comment]
Same issue here

**Comment by 0xDC00** [comment]
Fixed: https://github.com/0xDC00/scripts/commit/9061a4fe408bb5dddb14757d66ae9bc19b0f1eb7
Manual update via Agent: `Script... -> dropdown -> Update scripts`
